CREATE NONCLUSTERED INDEX [LocalGovernmentAreaID_OffenceID.Count.Year] ON [Crime].[Crime]
(
	[LocalGovernmentAreaID] ASC
)
INCLUDE
(
	[OffenceID],
	[Count],
	[Year]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


