#region Using References

using System;

using FluentMigrator;

#endregion

namespace CPT331.Data.Migration.Migrations
{
	[Migration(0002)]
	public class M0002 : FluentMigrator.Migration
	{
		public override void Down()
		{
			//	Nothing to see here
		}

		public override void Up()
		{
			Create.Schema("Crime");
			Create.Schema("Location");

			Create.Table("Crime")
				.InSchema("Crime")
					.WithColumn("ID")
						.AsInt32()
						.NotNullable()
						.Identity()
						.PrimaryKey()
					.WithColumn("LocalGovernmentAreaID")
						.AsInt32()
						.NotNullable()
					.WithColumn("OffenceID")
						.AsInt32()
						.NotNullable()
					.WithColumn("Count")
						.AsInt32()
						.NotNullable()
					.WithColumn("Month")
						.AsInt32()
						.NotNullable()
					.WithColumn("Year")
						.AsInt32()
						.NotNullable()
					.WithColumn("IsDeleted")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(false)
					.WithColumn("IsVisible")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(true)
					.WithColumn("DateCreatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime)
					.WithColumn("DateUpdatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime);

			Create.Table("LocalGovernmentArea")
				.InSchema("Location")
					.WithColumn("ID")
						.AsInt32()
						.NotNullable()
						.Identity()
						.PrimaryKey()
					.WithColumn("StateID")
						.AsInt32()
						.NotNullable()
					.WithColumn("Name")
						.AsAnsiString(100)
						.NotNullable()
					.WithColumn("IsDeleted")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(false)
					.WithColumn("IsVisible")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(true)
					.WithColumn("DateCreatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime)
					.WithColumn("DateUpdatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime);

			Create.Table("LocalGovernmentAreaLocation")
				.InSchema("Location")
					.WithColumn("LocalGovernmentAreaID")
						.AsInt32()
						.NotNullable()
						.PrimaryKey()
					.WithColumn("LocationID")
						.AsInt32()
						.NotNullable()
						.PrimaryKey();

			Create.Table("Location")
				.InSchema("Location")
					.WithColumn("ID")
						.AsInt32()
						.NotNullable()
						.Identity()
						.PrimaryKey()
					.WithColumn("StateID")
						.AsInt32()
						.NotNullable()
					.WithColumn("Name")
						.AsAnsiString(100)
						.NotNullable()
					.WithColumn("IsDeleted")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(false)
					.WithColumn("IsVisible")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(true)
					.WithColumn("DateCreatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime)
					.WithColumn("DateUpdatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime);

			Create.Table("Offence")
				.InSchema("Crime")
					.WithColumn("ID")
						.AsInt32()
						.NotNullable()
						.Identity()
						.PrimaryKey()
					.WithColumn("ParentID")
						.AsInt32()
						.Nullable()
					.WithColumn("Name")
						.AsAnsiString(100)
						.NotNullable()
					.WithColumn("IsDeleted")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(false)
					.WithColumn("IsVisible")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(true)
					.WithColumn("DateCreatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime)
					.WithColumn("DateUpdatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime);

			Create.Table("State")
				.InSchema("Location")
					.WithColumn("ID")
						.AsInt32()
						.NotNullable()
						.Identity()
						.PrimaryKey()
					.WithColumn("Name")
						.AsAnsiString(100)
						.NotNullable()
					.WithColumn("AbbreviatedName")
						.AsAnsiString(3)
						.NotNullable()
					.WithColumn("IsDeleted")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(false)
					.WithColumn("IsVisible")
						.AsBoolean()
						.NotNullable()
						.WithDefaultValue(true)
					.WithColumn("DateCreatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime)
					.WithColumn("DateUpdatedUtc")
						.AsDateTime()
						.NotNullable()
						.WithDefault(SystemMethods.CurrentUTCDateTime);

			Execute.EmbeddedScript("M0002.sql");
		}
	}
}