# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CPT331.iOS' do
  use_frameworks!

  pod 'Mapbox-iOS-SDK', '~> 3.3.4'
  pod 'MapboxGeocoder.swift', :git => 'https://github.com/mapbox/MapboxGeocoder.swift.git', :tag => 'v0.5.0'
  pod 'AlamofireSwiftyJSON'
  pod 'SideMenu'
  pod 'MXParallaxHeader'
  pod 'Charts'
end
