# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'CPT331.iOS' do
  use_frameworks!

  pod 'Mapbox-iOS-SDK', '~> 3.3.4'
  pod 'CSVImporter', '~> 1.1'
  pod 'SVProgressHUD'
  pod 'AlamofireSwiftyJSON'
  pod 'SideMenu'
  pod 'BGTableViewRowActionWithImage'

end
